// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/models/card_details.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8158138168438795910),
    name: 'CardDetails',
    lastPropertyId: const obx_int.IdUid(6, 8409486368122835459),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3655173470605536143),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1557575503763659051),
        name: 'cardHolderName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1169018243372704809),
        name: 'cardNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 624230779410839915),
        name: 'expiryDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8580875240472653137),
        name: 'cvv',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8409486368122835459),
        name: 'cardType',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 8158138168438795910),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CardDetails: obx_int.EntityDefinition<CardDetails>(
      model: _entities[0],
      toOneRelations: (CardDetails object) => [],
      toManyRelations: (CardDetails object) => {},
      getId: (CardDetails object) => object.id,
      setId: (CardDetails object, int id) {
        object.id = id;
      },
      objectToFB: (CardDetails object, fb.Builder fbb) {
        final cardHolderNameOffset = fbb.writeString(object.cardHolderName);
        final cardNumberOffset = fbb.writeString(object.cardNumber);
        final expiryDateOffset = fbb.writeString(object.expiryDate);
        final cvvOffset = fbb.writeString(object.cvv);
        final cardTypeOffset = fbb.writeString(object.cardType);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, cardHolderNameOffset);
        fbb.addOffset(2, cardNumberOffset);
        fbb.addOffset(3, expiryDateOffset);
        fbb.addOffset(4, cvvOffset);
        fbb.addOffset(5, cardTypeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final cardHolderNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final cardNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final expiryDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final cvvParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final cardTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = CardDetails(
          cardHolderName: cardHolderNameParam,
          cardNumber: cardNumberParam,
          expiryDate: expiryDateParam,
          cvv: cvvParam,
          cardType: cardTypeParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CardDetails] entity fields to define ObjectBox queries.
class CardDetails_ {
  /// See [CardDetails.id].
  static final id = obx.QueryIntegerProperty<CardDetails>(
    _entities[0].properties[0],
  );

  /// See [CardDetails.cardHolderName].
  static final cardHolderName = obx.QueryStringProperty<CardDetails>(
    _entities[0].properties[1],
  );

  /// See [CardDetails.cardNumber].
  static final cardNumber = obx.QueryStringProperty<CardDetails>(
    _entities[0].properties[2],
  );

  /// See [CardDetails.expiryDate].
  static final expiryDate = obx.QueryStringProperty<CardDetails>(
    _entities[0].properties[3],
  );

  /// See [CardDetails.cvv].
  static final cvv = obx.QueryStringProperty<CardDetails>(
    _entities[0].properties[4],
  );

  /// See [CardDetails.cardType].
  static final cardType = obx.QueryStringProperty<CardDetails>(
    _entities[0].properties[5],
  );
}
